# Dockerfile.jenkins
FROM jenkins/jenkins:2.492.2-lts-jdk17

USER root

# Установка Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean

# Возвращаемся к пользователю Jenkins
USER jenkins
